openapi: 3.0.3
info:
  title: RemoteLight API
  description: REST API for interacting with a RemoteLight instance.
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.txt
  contact:
    name: GitHub
    url: https://github.com/RemoteLight/RemoteLight
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /outputs:
    get:
      summary: Get all outputs
      tags:
        - Outputs
      responses:
        200:
          description: A list of all stored outputs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutputResponseModel"
    post:
      summary: Create new output
      tags:
        - Outputs
      requestBody:
        $ref: "#/components/requestBodies/OutputRequestModel"
      responses:
        201:
          $ref: "#/components/responses/OutputResponseModel"
  /outputs/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get single output
      tags:
        - Outputs
      responses:
        200:
          $ref: "#/components/responses/OutputResponseModel"
        400:
          $ref: "#/components/responses/MissingIdError"
        404:
          $ref: "#/components/responses/OutputNotFoundError"
    delete:
      summary: Delete output
      tags:
        - Outputs
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Output removed
        400:
          $ref: "#/components/responses/MissingIdError"
        404:
          $ref: "#/components/responses/OutputNotFoundError"

components:
  responses:
    MissingIdError:
      description: Missing id
      content:
        application/json:
          schema:
            type: object
            properties:
              exception:
                type: string
                nullable: true
                example: null
              message:
                type: string
                example: Missing or malformed id
    OutputNotFoundError:
      description: Output not found
      content:
        application/json:
          schema:
            type: object
            properties:
              exception:
                type: string
                nullable: true
                example: null
              message:
                type: string
                example: No output with id $id
    OutputResponseModel:
      description: Output model
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OutputResponseModel"
  requestBodies:
    OutputRequestModel:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OutputRequestModel"
  schemas:
    OutputResponseModel:
      type: object
      properties:
        id:
          type: string
          description: Unique UUID
          example: "82d85de8-aed3-4e5d-8665-28efef6178fa"
        identifier:
          $ref: "#/components/schemas/OutputIdentifier"
        properties:
          type: object
          oneOf:
            - $ref: "#/components/schemas/SerialOutputProperties"
    OutputRequestModel:
      type: object
      required:
        - identifier
      properties:
        identifier:
          $ref: "#/components/schemas/OutputIdentifier"
        properties:
          type: object
          oneOf:
            - $ref: "#/components/schemas/SerialOutputProperties"
    DefaultOutputProperties:
      type: object
      properties:
        pixels:
          type: integer
          example: 60
        name:
          type: string
          description: User defined output name.
          example: "My Output"
        color_order:
          $ref: "#/components/schemas/ColorOrder"
        gamma_correction:
          type: boolean
    SerialOutputProperties:
      type: object
      allOf:
        - $ref: "#/components/schemas/DefaultOutputProperties"
        - properties:
            baud_rate:
              type: integer
              example: 1000000
            port_descriptor:
              type: string
              nullable: true
              description: Serial Port name.
              example: "COM5"
    OutputIdentifier:
      type: string
      enum:
        - "serial_glediator"
        - "serial_adalight"
        - "serial_tpm2"
    ColorOrder:
      type: string
      enum:
        - RGB
        - RBG
        - GRB
        - GBR
        - BRG
        - BGR
        - WRGB
        - WRBG
        - WGRB
        - WGBR
        - WBRG
        - WBGR
        - RWGB
        - RWBG
        - RGWB
        - RGBW
        - RBWG
        - RBGW
        - GWRB
        - GWBR
        - GRWB
        - GRBW
        - GBWR
        - GBRW
        - BWRG
        - BWGR
        - BRWG
        - BRGW
        - BGWR
        - BGRW
