openapi: 3.0.3
info:
  title: RemoteLight API
  description: |
    ## REST API for interacting with RemoteLight
    RemoteLight is a Multifunctional LED Control Software for adressable LED strips.
    This API can be used to manage outputs and scenes and control effects for a RemoteLight instance.
    The implementation can be found on this [GitHub repository](https://github.com/RemoteLight/RemoteLight).
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.txt
  contact:
    name: GitHub
    url: https://github.com/RemoteLight/RemoteLight
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Local Server

paths:
  /outputs:
    $ref: "./paths/outputs.yaml"
  /outputs/{id}:
    $ref: "./paths/output.yaml"

  /scenes:
    $ref: "./paths/scenes.yaml"
  /scenes/{id}:
    $ref: "./paths/scene.yaml"

  /registries/outputs:
    $ref: "./paths/registriesOutputs.yaml"
  /registries/effects:
    $ref: "./paths/registriesEffects.yaml"

components:
  responses:
    $ref: "./responses/index.yaml"
  schemas:
    $ref: "./schemas/index.yaml"
